receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318" # Receives OTLP data via HTTP on port 4318

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889" # Exposes pipeline metrics on port 8889 for Prometheus scraping
    const_labels:
      label1: value1

  otlphttp:
    endpoint: "http://tempo:3200" # Exports traces to Tempo via HTTP on port 3200
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
# telemetry:
#   metrics:
#     address: "0.0.0.0:8888"
#     level: basic
