server:
  http_listen_port: 9080 # Matches Promtail's exposed port in Docker Compose

positions:
  filename: /tmp/positions.yaml # Keeps track of last read log position

clients:
  - url: "http://loki:3100/loki/api/v1/push" # Matches Loki service name in Docker Compose

scrape_configs:
  - job_name: "docker-logs"
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_image]
        target_label: image
      - source_labels: [__meta_docker_network]
        target_label: network
      - source_labels: [__meta_docker_container_id]
        target_label: container_id

  - job_name: "traefik-logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "traefik"
          container: "traefik"
          filename: "/var/log/traefik/access.log"

  - job_name: "application-logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "application"
          container: "all-services"
          filename: "/var/log/app.log"
