global:
  scrape_interval: 5s # Reduced interval for more frequent metric updates
  evaluation_interval: 5s

scrape_configs:
  # 🔹 Traefik Metrics
  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8899"]
    metrics_path: "/metrics"
    relabel_configs:
      - source_labels: [__address__]
        target_label: job
        replacement: "traefik"

  # 🔹 Loki Metrics
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
    metrics_path: "/metrics"
    relabel_configs:
      - source_labels: [__address__]
        target_label: job
        replacement: "loki"

  # 🔹 Prometheus Self-Monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    metrics_path: "/metrics"
    relabel_configs:
      - source_labels: [__address__]
        target_label: job
        replacement: "prometheus"

  # 🔹 cAdvisor - Per Container Metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    metrics_path: "/metrics"
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_image]
        target_label: image
      - source_labels: [__meta_docker_network]
        target_label: network

  # 🔹 Promtail (Log Monitoring)
  - job_name: "promtail"
    static_configs:
      - targets: ["promtail:9080"]
    metrics_path: "/metrics"
    relabel_configs:
      - source_labels: [__address__]
        target_label: job
        replacement: "promtail"

  # 🔹 Node Exporter (System Metrics)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    metrics_path: "/metrics"
    relabel_configs:
      - source_labels: [__address__]
        target_label: job
        replacement: "node"

  # - job_name: "otel-collector"
  #   static_configs:
  #     - targets: ["otel-collector:8889"]
